begin;

create table public.migrations (
    id bigint generated by default as identity primary key,
    migration varchar(255) not null,
    batch integer not null
);

create table public.users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    email_verified_at timestamptz,
    password varchar(255) not null,
    remember_token varchar(100),
    role varchar(255) not null default 'limited' check (role in ('full', 'limited')),
    supabase_user_id uuid unique references auth.users(id) on delete cascade,
    created_at timestamptz,
    updated_at timestamptz
);

create table public.password_reset_tokens (
    email varchar(255) primary key,
    token varchar(255) not null,
    created_at timestamptz
);

create table public.sessions (
    id varchar(255) primary key,
    user_id bigint,
    ip_address varchar(45),
    user_agent text,
    payload text not null,
    last_activity integer not null
);
create index sessions_user_id_index on public.sessions (user_id);
create index sessions_last_activity_index on public.sessions (last_activity);

create table public.cache (
    key varchar(255) primary key,
    value text not null,
    expiration integer not null
);
create index cache_expiration_index on public.cache (expiration);

create table public.cache_locks (
    key varchar(255) primary key,
    owner varchar(255) not null,
    expiration integer not null
);
create index cache_locks_expiration_index on public.cache_locks (expiration);

create table public.jobs (
    id bigint generated by default as identity primary key,
    queue varchar(255) not null,
    payload text not null,
    attempts smallint not null,
    reserved_at integer,
    available_at integer not null,
    created_at integer not null
);
create index jobs_queue_index on public.jobs (queue);

create table public.job_batches (
    id varchar(255) primary key,
    name varchar(255) not null,
    total_jobs integer not null,
    pending_jobs integer not null,
    failed_jobs integer not null,
    failed_job_ids text not null,
    options text,
    cancelled_at integer,
    created_at integer not null,
    finished_at integer
);

create table public.failed_jobs (
    id bigint generated by default as identity primary key,
    uuid varchar(255) not null unique,
    connection text not null,
    queue text not null,
    payload text not null,
    exception text not null,
    failed_at timestamptz not null default now()
);

create table public.services (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    slug varchar(255) not null unique,
    description text,
    icon varchar(255),
    is_featured boolean not null default false,
    is_enabled boolean not null default true,
    created_at timestamptz,
    updated_at timestamptz
);
create index services_is_enabled_index on public.services (is_enabled);

create table public.packages (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    slug varchar(255) not null unique,
    description text,
    price numeric(12, 2) not null default 0,
    min_guests integer not null default 0,
    max_guests integer not null default 0,
    menu text,
    freebies text,
    addons text,
    event_type varchar(255),
    is_featured boolean not null default false,
    image_path varchar(255),
    created_at timestamptz,
    updated_at timestamptz
);
create index packages_price_index on public.packages (price);

create table public.clients (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    phone varchar(255),
    address text,
    created_at timestamptz,
    updated_at timestamptz
);

create table public.reservations (
    id bigint generated by default as identity primary key,
    client_id bigint references public.clients(id) on delete set null,
    package_id bigint references public.packages(id) on delete set null,
    full_name varchar(255) not null,
    contact_number varchar(255) not null,
    email varchar(255) not null,
    address varchar(255) not null,
    event_type varchar(255) not null,
    event_date date not null,
    event_time varchar(255) not null,
    venue varchar(255) not null,
    guest_count integer not null,
    estimated_budget numeric(12, 2) not null default 0,
    total_cost numeric(12, 2),
    additional_services text,
    special_requests text,
    additional_notes text,
    service_contract varchar(255),
    service_contracts jsonb,
    status varchar(255) not null default 'pending',
    reservation_code varchar(255) unique,
    payment_status varchar(255) not null default 'Unpaid',
    payment_type varchar(255),
    amount_paid numeric(10, 2) not null default 0,
    balance numeric(10, 2) not null default 0,
    created_at timestamptz,
    updated_at timestamptz
);
create index reservations_event_date_status_index on public.reservations (event_date, status);
create index reservations_payment_status_index on public.reservations (payment_status);
create index reservations_created_at_index on public.reservations (created_at);

create table public.inquiries (
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null,
    contact_number varchar(255) not null,
    email varchar(255) not null,
    subject varchar(255) not null,
    category varchar(255) not null,
    message text not null,
    admin_reply text,
    replied_at timestamptz,
    status varchar(255) not null default 'new',
    created_at timestamptz,
    updated_at timestamptz
);
create index inquiries_status_created_at_index on public.inquiries (status, created_at);

create table public.activity_logs (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    actor_name varchar(255),
    actor_email varchar(255),
    actor_role varchar(20),
    action varchar(255) not null,
    method varchar(12),
    ip_address varchar(45),
    activity_date date not null,
    activity_time time not null,
    description text,
    created_at timestamptz,
    updated_at timestamptz
);
create index activity_logs_actor_email_created_at_index on public.activity_logs (actor_email, created_at);

create table public.settings (
    id bigint generated by default as identity primary key,
    key varchar(255) not null unique,
    value text,
    created_at timestamptz,
    updated_at timestamptz
);

create table public.notification_templates (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    type varchar(255) not null,
    body text,
    created_at timestamptz,
    updated_at timestamptz
);

create table public.gallery_items (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description text,
    image_path varchar(255) not null,
    event_type varchar(255),
    is_featured boolean not null default false,
    created_at timestamptz,
    updated_at timestamptz
);
create index gallery_items_created_at_index on public.gallery_items (created_at);

insert into public.migrations (migration, batch) values
    ('0001_01_01_000000_create_users_table', 1),
    ('0001_01_01_000001_create_cache_table', 1),
    ('0001_01_01_000002_create_jobs_table', 1),
    ('2024_01_01_000000_create_services_table', 1),
    ('2024_01_01_000001_create_packages_table', 1),
    ('2024_01_01_000002_create_clients_table', 1),
    ('2024_01_01_000003_create_reservations_table', 1),
    ('2024_01_01_000004_create_inquiries_table', 1),
    ('2024_01_01_000005_create_activity_logs_table', 1),
    ('2024_01_01_000006_create_settings_table', 1),
    ('2024_01_01_000007_create_notification_templates_table', 1),
    ('2026_07_26_000000_add_signature_catering_packages', 1),
    ('2026_07_26_000001_add_role_to_users_table', 1),
    ('2026_08_13_000000_add_reply_to_inquiries_table', 1),
    ('2026_08_13_000001_create_gallery_items_table', 1),
    ('2026_08_13_000002_add_actor_details_to_activity_logs_table', 1),
    ('2026_09_09_000000_add_service_contract_to_reservations_table', 1),
    ('2026_09_09_000001_add_service_contracts_to_reservations_table', 1),
    ('2026_09_19_000000_add_reservation_code_to_reservations_table', 1),
    ('2026_09_20_000000_add_payment_details_to_reservations_table', 1),
    ('2026_09_20_000001_fix_missing_payment_columns_in_reservations_table', 1),
    ('2026_09_23_000000_add_total_cost_to_reservations_table', 1),
    ('2026_09_23_000001_add_enabled_to_services_table', 1),
    ('2026_09_26_000000_add_image_path_to_packages_table', 1),
    ('2026_09_26_000001_add_supabase_auth_id_to_users_table', 1);

insert into public.packages
    (name, slug, description, price, min_guests, max_guests, menu, freebies, addons, event_type, is_featured, created_at, updated_at)
values
    ('Silver', 'silver', 'A generous, polished buffet for relaxed celebrations and intimate gatherings.', 550, 30, 80, '2 mains, pasta or noodles, vegetables, rice, dessert, and iced tea', 'Basic buffet styling, menu labels, and trained service crew', 'Dessert station, tablescape styling, and additional mains', 'Birthdays, reunions, and simple celebrations', false, now(), now()),
    ('Gold', 'gold', 'A crowd-pleasing selection with elevated presentation for milestone moments.', 750, 50, 150, '3 mains, pasta, vegetables, rice, dessert station, and refreshments', 'Styled buffet setup, menu labels, basic floral accents, and service crew', 'Grazing table, mocktail bar, and upgraded styling', 'Debuts, anniversaries, and company events', true, now(), now()),
    ('Platinum', 'platinum', 'A refined menu and fuller service for memorable celebrations with more to share.', 950, 80, 250, '4 mains, pasta, vegetables, rice, premium dessert station, and drinks', 'Enhanced tablescape, welcome drinks, menu labels, and dedicated event lead', 'Live station, mobile bar, and premium floral styling', 'Weddings, launches, and formal celebrations', false, now(), now()),
    ('Diamond', 'diamond', 'Our most complete celebration experience, tailored for grand and unforgettable events.', 1250, 120, 400, '5 mains, live station, pasta, vegetables, rice, premium desserts, and drinks', 'Full event styling consultation, upgraded tablescape, service team, and event lead', 'Custom menu development, lounge setup, and premium bar service', 'Luxury weddings, gala dinners, and large-scale events', false, now(), now());

create or replace function public.current_admin_role(required_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.users
        where supabase_user_id = auth.uid()
          and role = any(required_roles)
    );
$$;
revoke all on function public.current_admin_role(text[]) from public;
grant execute on function public.current_admin_role(text[]) to authenticated;

alter table public.migrations enable row level security;
alter table public.users enable row level security;
alter table public.password_reset_tokens enable row level security;
alter table public.sessions enable row level security;
alter table public.cache enable row level security;
alter table public.cache_locks enable row level security;
alter table public.jobs enable row level security;
alter table public.job_batches enable row level security;
alter table public.failed_jobs enable row level security;
alter table public.services enable row level security;
alter table public.packages enable row level security;
alter table public.clients enable row level security;
alter table public.reservations enable row level security;
alter table public.inquiries enable row level security;
alter table public.activity_logs enable row level security;
alter table public.settings enable row level security;
alter table public.notification_templates enable row level security;
alter table public.gallery_items enable row level security;

revoke all on public.migrations, public.password_reset_tokens, public.sessions, public.cache, public.cache_locks,
    public.jobs, public.job_batches, public.failed_jobs from anon, authenticated;

grant select on public.users to authenticated;
grant select on public.services, public.packages, public.gallery_items to anon, authenticated;
grant select, insert, update, delete on public.services, public.packages, public.gallery_items to authenticated;
grant select on public.clients to authenticated;
grant select, insert, update on public.reservations to authenticated;
grant select, insert, update, delete on public.inquiries to authenticated;
grant select on public.activity_logs to authenticated;
grant select, insert, update, delete on public.settings, public.notification_templates to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy users_read_self_or_full_admin on public.users
    for select to authenticated
    using (supabase_user_id = auth.uid() or public.current_admin_role(array['full']));
create policy users_manage_full_admin on public.users
    for all to authenticated
    using (public.current_admin_role(array['full']))
    with check (public.current_admin_role(array['full']));

create policy services_read_enabled on public.services
    for select to anon, authenticated using (is_enabled);
create policy services_manage_full_admin on public.services
    for all to authenticated
    using (public.current_admin_role(array['full']))
    with check (public.current_admin_role(array['full']));

create policy packages_read_public on public.packages
    for select to anon, authenticated using (true);
create policy packages_manage_full_admin on public.packages
    for all to authenticated
    using (public.current_admin_role(array['full']))
    with check (public.current_admin_role(array['full']));

create policy gallery_read_public on public.gallery_items
    for select to anon, authenticated using (true);
create policy gallery_manage_full_admin on public.gallery_items
    for all to authenticated
    using (public.current_admin_role(array['full']))
    with check (public.current_admin_role(array['full']));

create policy clients_read_admins on public.clients
    for select to authenticated
    using (public.current_admin_role(array['full', 'limited']));

create policy reservations_read_admins on public.reservations
    for select to authenticated
    using (public.current_admin_role(array['full', 'limited']));
create policy reservations_create_admins on public.reservations
    for insert to authenticated
    with check (public.current_admin_role(array['full', 'limited']));
create policy reservations_update_admins on public.reservations
    for update to authenticated
    using (public.current_admin_role(array['full', 'limited']))
    with check (public.current_admin_role(array['full', 'limited']));

create policy inquiries_read_admins on public.inquiries
    for select to authenticated
    using (public.current_admin_role(array['full', 'limited']));
create policy inquiries_create_admins on public.inquiries
    for insert to authenticated
    with check (public.current_admin_role(array['full', 'limited']));
create policy inquiries_update_admins on public.inquiries
    for update to authenticated
    using (public.current_admin_role(array['full', 'limited']))
    with check (public.current_admin_role(array['full', 'limited']));
create policy inquiries_delete_admins on public.inquiries
    for delete to authenticated
    using (public.current_admin_role(array['full', 'limited']));

create policy activity_logs_read_full_admin on public.activity_logs
    for select to authenticated
    using (public.current_admin_role(array['full']));
create policy settings_manage_full_admin on public.settings
    for all to authenticated
    using (public.current_admin_role(array['full']))
    with check (public.current_admin_role(array['full']));
create policy notification_templates_manage_full_admin on public.notification_templates
    for all to authenticated
    using (public.current_admin_role(array['full']))
    with check (public.current_admin_role(array['full']));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('catering-media', 'catering-media', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy catering_media_public_read on storage.objects
    for select to anon, authenticated
    using (bucket_id = 'catering-media');
create policy catering_media_full_admin_insert on storage.objects
    for insert to authenticated
    with check (bucket_id = 'catering-media' and public.current_admin_role(array['full']));
create policy catering_media_full_admin_update on storage.objects
    for update to authenticated
    using (bucket_id = 'catering-media' and public.current_admin_role(array['full']))
    with check (bucket_id = 'catering-media' and public.current_admin_role(array['full']));
create policy catering_media_full_admin_delete on storage.objects
    for delete to authenticated
    using (bucket_id = 'catering-media' and public.current_admin_role(array['full']));

commit;